steps:
  - label: ":package: Maven build"
    plugins:
        - madan712/java-maven:
        
  - wait
  
  - label: ":whale: Terraform"
    command:
        - terraform init && terraform apply -auto-approve -var build=${buildkite-agent meta-data get build_path}
        - echo "Uploaded to AWS!"
        