steps:
  - label: ":package: Maven build"
    command: mvn package
  - label: ":whale: Terraform"
    command:
        - terraform init && terraform apply -input=false
        - echo "Uploaded to AWS!"